import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, IconButton, InputAdornment, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TablePagination, TableRow, TextField, Typography } from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutline";
import EditOutlinedIcon from "@mui/icons-material/EditOutlined";
import RefreshIcon from "@mui/icons-material/Refresh";
import SearchIcon from "@mui/icons-material/Search";
import { isAxiosError } from "axios";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { PageIntro } from "../../components/common/PageIntro";
import { createAdminVoucher, deleteAdminVoucher, getAdminVouchers, updateAdminVoucher, type Voucher, type VoucherPayload } from "../../services/voucherService";
import { toDateTimeLocalValue } from "../../utils/dateTime";

type VoucherForm = Omit<VoucherPayload, "startsAt" | "endsAt"> & { startsAt: string; endsAt: string };
const emptyForm: VoucherForm = { code: "", name: "", discountType: "PERCENT", discountValue: 10, maxDiscount: null, minimumOrder: 0, usageLimit: null, perUserLimit: 1, startsAt: "", endsAt: "", active: true };
const money = (amount: number) => new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND" }).format(amount);
const getError = (error: unknown, fallback: string) => isAxiosError<{ message?: string }>(error) ? error.response?.data?.message || fallback : fallback;

export function AdminVouchersPage() {
  const [data, setData] = useState<Voucher[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(0); const [size, setSize] = useState(10);
  const [keyword, setKeyword] = useState(""); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(false);
  const [feedback, setFeedback] = useState<{ type: "success" | "error"; text: string } | null>(null);
  const [dialog, setDialog] = useState(false); const [editing, setEditing] = useState<Voucher | null>(null); const [form, setForm] = useState<VoucherForm>(emptyForm); const [submitting, setSubmitting] = useState(false);
  const [deleting, setDeleting] = useState<Voucher | null>(null);

  const load = useCallback(async () => { setLoading(true); try { const result = await getAdminVouchers(search, page, size); setData(result.items); setTotal(result.totalElements); } catch (error) { setFeedback({ type: "error", text: getError(error, "Không thể tải danh sách voucher.") }); } finally { setLoading(false); } }, [page, search, size]);
  useEffect(() => { void load(); }, [load]);
  const openCreate = () => { setEditing(null); setForm(emptyForm); setDialog(true); };
  const openEdit = (voucher: Voucher) => { setEditing(voucher); setForm({ code: voucher.code, name: voucher.name, discountType: voucher.discountType, discountValue: voucher.discountValue, maxDiscount: voucher.maxDiscount ?? null, minimumOrder: voucher.minimumOrder, usageLimit: voucher.usageLimit ?? null, perUserLimit: voucher.perUserLimit, startsAt: toDateTimeLocalValue(voucher.startsAt), endsAt: toDateTimeLocalValue(voucher.endsAt), active: voucher.active }); setDialog(true); };
  const toPayload = (): VoucherPayload => ({ ...form, code: form.code.trim().toUpperCase(), name: form.name.trim(), startsAt: new Date(form.startsAt).toISOString(), endsAt: new Date(form.endsAt).toISOString(), maxDiscount: form.discountType === "PERCENT" && form.maxDiscount ? Number(form.maxDiscount) : null, usageLimit: form.usageLimit ? Number(form.usageLimit) : null, minimumOrder: Number(form.minimumOrder), perUserLimit: Number(form.perUserLimit), discountValue: Number(form.discountValue) });
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.code.trim() || !form.name.trim() || !form.startsAt || !form.endsAt) { setFeedback({ type: "error", text: "Vui lòng nhập đủ mã, tên và thời gian áp dụng." }); return; } if (new Date(form.endsAt) <= new Date(form.startsAt)) { setFeedback({ type: "error", text: "Thời gian kết thúc phải sau thời gian bắt đầu." }); return; } setSubmitting(true); try { const payload = toPayload(); if (editing) await updateAdminVoucher(editing.id, payload); else await createAdminVoucher(payload); setFeedback({ type: "success", text: editing ? "Cập nhật voucher thành công." : "Tạo voucher thành công." }); setDialog(false); await load(); } catch (error) { setFeedback({ type: "error", text: getError(error, "Không thể lưu voucher.") }); } finally { setSubmitting(false); } };
  const confirmDelete = async () => { if (!deleting) return; setSubmitting(true); try { await deleteAdminVoucher(deleting.id); setFeedback({ type: "success", text: "Xoá voucher thành công." }); setDeleting(null); await load(); } catch (error) { setFeedback({ type: "error", text: getError(error, "Không thể xoá voucher.") }); } finally { setSubmitting(false); } };

  return <Stack spacing={3}><PageIntro eyebrow="Khuyến mãi" title="Quản lý mã giảm giá" description="Tạo, cập nhật và kiểm soát điều kiện sử dụng voucher." action={<Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<RefreshIcon />} onClick={() => void load()} disabled={loading}>Làm mới</Button><Button variant="contained" startIcon={<AddIcon />} onClick={openCreate}>Tạo voucher</Button></Stack>} />
    {feedback && <Alert severity={feedback.type} onClose={() => setFeedback(null)}>{feedback.text}</Alert>}
    <Card><CardContent><Stack component="form" onSubmit={(event) => { event.preventDefault(); setPage(0); setSearch(keyword.trim()); }} direction={{ xs: "column", sm: "row" }} spacing={1}><TextField size="small" value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="Tìm mã hoặc tên voucher" sx={{ minWidth: 280 }} slotProps={{ input: { startAdornment: <InputAdornment position="start"><SearchIcon fontSize="small" /></InputAdornment> } }} /><Button type="submit" variant="contained">Tìm kiếm</Button></Stack></CardContent></Card>
    <Paper><TableContainer><Table aria-label="Danh sách voucher"><TableHead><TableRow><TableCell>Mã / tên</TableCell><TableCell>Ưu đãi</TableCell><TableCell>Điều kiện</TableCell><TableCell>Thời hạn</TableCell><TableCell>Trạng thái</TableCell><TableCell align="right">Thao tác</TableCell></TableRow></TableHead><TableBody>{loading ? <TableRow><TableCell colSpan={6} align="center">Đang tải...</TableCell></TableRow> : data.length === 0 ? <TableRow><TableCell colSpan={6} align="center">Chưa có voucher.</TableCell></TableRow> : data.map((voucher) => <TableRow key={voucher.id} hover><TableCell><Typography fontWeight={700}>{voucher.code}</Typography><Typography variant="body2" color="text.secondary">{voucher.name}</Typography></TableCell><TableCell>{voucher.discountType === "PERCENT" ? `${voucher.discountValue}%${voucher.maxDiscount ? `, tối đa ${money(voucher.maxDiscount)}` : ""}` : money(voucher.discountValue)}</TableCell><TableCell>Từ {money(voucher.minimumOrder)}<br />Đã dùng {voucher.usedCount}{voucher.usageLimit ? `/${voucher.usageLimit}` : ""}</TableCell><TableCell>{new Date(voucher.startsAt).toLocaleDateString("vi-VN")}<br />{new Date(voucher.endsAt).toLocaleDateString("vi-VN")}</TableCell><TableCell><Chip size="small" color={voucher.active ? "success" : "default"} label={voucher.active ? "Đang bật" : "Đã tắt"} /></TableCell><TableCell align="right"><IconButton aria-label={`Sửa ${voucher.code}`} onClick={() => openEdit(voucher)}><EditOutlinedIcon /></IconButton><IconButton aria-label={`Xoá ${voucher.code}`} color="error" onClick={() => setDeleting(voucher)}><DeleteOutlineIcon /></IconButton></TableCell></TableRow>)}</TableBody></Table></TableContainer><TablePagination component="div" count={total} page={page} rowsPerPage={size} rowsPerPageOptions={[5,10,25]} onPageChange={(_, next) => setPage(next)} onRowsPerPageChange={(event) => { setSize(Number(event.target.value)); setPage(0); }} labelRowsPerPage="Số hàng:" /></Paper>
    <Dialog open={dialog} onClose={() => !submitting && setDialog(false)} fullWidth maxWidth="sm"><Box component="form" onSubmit={submit}><DialogTitle>{editing ? "Cập nhật voucher" : "Tạo voucher"}</DialogTitle><DialogContent><Stack spacing={2} mt={1}><Stack direction={{ xs: "column", sm: "row" }} spacing={2}><TextField label="Mã voucher" required value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase() })} fullWidth /><TextField label="Tên voucher" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} fullWidth /></Stack><TextField select label="Loại giảm" value={form.discountType} onChange={(event) => setForm({ ...form, discountType: event.target.value as VoucherForm["discountType"] })} slotProps={{ select: { native: true } }}><option value="PERCENT">Phần trăm (%)</option><option value="FIXED">Số tiền cố định</option></TextField><Stack direction={{ xs: "column", sm: "row" }} spacing={2}><TextField type="number" label={form.discountType === "PERCENT" ? "Giá trị (%)" : "Giá trị (đ)"} required value={form.discountValue} onChange={(event) => setForm({ ...form, discountValue: Number(event.target.value) })} fullWidth /><TextField type="number" label="Đơn tối thiểu (đ)" value={form.minimumOrder} onChange={(event) => setForm({ ...form, minimumOrder: Number(event.target.value) })} fullWidth /></Stack>{form.discountType === "PERCENT" && <TextField type="number" label="Giảm tối đa (đ, không bắt buộc)" value={form.maxDiscount ?? ""} onChange={(event) => setForm({ ...form, maxDiscount: event.target.value ? Number(event.target.value) : null })} />}<Stack direction={{ xs: "column", sm: "row" }} spacing={2}><TextField type="number" label="Tổng lượt dùng" value={form.usageLimit ?? ""} onChange={(event) => setForm({ ...form, usageLimit: event.target.value ? Number(event.target.value) : null })} fullWidth /><TextField type="number" label="Lượt/khách" value={form.perUserLimit} onChange={(event) => setForm({ ...form, perUserLimit: Number(event.target.value) })} fullWidth /></Stack><Stack direction={{ xs: "column", sm: "row" }} spacing={2}><TextField type="datetime-local" label="Bắt đầu" required value={form.startsAt} onChange={(event) => setForm({ ...form, startsAt: event.target.value })} slotProps={{ inputLabel: { shrink: true } }} fullWidth /><TextField type="datetime-local" label="Kết thúc" required value={form.endsAt} onChange={(event) => setForm({ ...form, endsAt: event.target.value })} slotProps={{ inputLabel: { shrink: true } }} fullWidth /></Stack><FormControlLabel control={<Checkbox checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} />} label="Đang kích hoạt" /></Stack></DialogContent><DialogActions><Button onClick={() => setDialog(false)} disabled={submitting}>Huỷ</Button><Button type="submit" variant="contained" disabled={submitting}>{submitting ? "Đang lưu..." : "Lưu"}</Button></DialogActions></Box></Dialog>
    <Dialog open={Boolean(deleting)} onClose={() => !submitting && setDeleting(null)}><DialogTitle>Xoá voucher?</DialogTitle><DialogContent>Voucher đã có lịch sử sử dụng không thể xoá để giữ dữ liệu đơn hàng.</DialogContent><DialogActions><Button onClick={() => setDeleting(null)}>Huỷ</Button><Button color="error" variant="contained" disabled={submitting} onClick={() => void confirmDelete()}>Xoá</Button></DialogActions></Dialog>
  </Stack>;
}
