export const ROUTES = {
  home: '/',
  products: '/products',
  productDetail: '/products/:slug',
  cart: '/cart',
  checkout: '/checkout',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  profile: '/account/profile',
  admin: '/admin',
  adminProducts: '/admin/products',
  adminOrders: '/admin/orders',
} as const
