export const ROUTES = {
  home: "/",
  products: "/products",
  productDetail: "/products/:slug",
  cart: "/cart",
  checkout: "/checkout",
  orderConfirmation: "/order-confirmation/:orderNumber",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  profile: "/account/profile",
  addresses: "/account/addresses",
  orders: "/account/orders",
  orderDetail: "/account/orders/:id",
  forbidden: "/forbidden",
  admin: "/admin",
  adminLogin: "/admin/login",
  adminUsers: "/admin/users",
  adminCategories: "/admin/categories",
  adminBrands: "/admin/brands",
  adminProducts: "/admin/products",
  adminInventory: "/admin/inventory",
  adminOrders: "/admin/orders",
  adminOrderDetail: "/admin/orders/:id",
} as const;
